### ISSUE TITLE
BUG: RadolanCanvas mouse and key events

### ISSUE THREAD

**Issue by kmuehlbauer** [wradlib/wradvis#11]
When used the PanZoom Camera (mouse wheel, mouse drag, mouse click etc.), all consecutive `key_press`-events are processed by RadolanCanvas (PanZoomCamera) only. The `keyPressEvent` in the gui isn't triggered any more.

We could propagate the event to the main gui by implementing a signal, but the RadolanCanvas (vispy) event is not of type QKeyEvent. 

So we will need some switching in the main gui. See #10 for a fix.

**Comment by heistermann** [comment]
Wow, that's nasty. Merge as you see fit!

**Comment by kmuehlbauer** [comment]
Solved by #10
