### ISSUE TITLE
GUI Layout

### ISSUE THREAD

**Issue by kmuehlbauer** [wradlib/wradvis#13]
# Current layout

 QSplitter (QtCore.Qt.Horizontal) with three Widgets (`PropertiesWidget`,  `RadolanWidget`, `MplWidget`). Only one of the latter two shown at one time.

**PropertiesWidget**
- [x] MenuBar (File)
- [x] SourceBox
- [x] MediaBox (date, time, play/pause, ffw, rev, slider, speedslider)
- [x] MouseBox (XY, LL mouse position)
- [x] Widget to define a time window that subsets data, see #16 

**Tooltips**
- [ ] use tooltips, where appropriate (the media-buttons already have tooltips), this will be done subsequently

**Widgetify** see #15 
- [x] MediaBox
- [x] SourceBox
- [x] MouseBox

We can move those current PropertiesWidget Boxes to separate Widgets, which can be added to the GUI as wanted (see #15).

**Comment by heistermann** [comment]
Sounds reasonable to define seperate widgets for each tool. Then we can use it as a tool box.

**Comment by kmuehlbauer** [comment]
For subsetting Time Ranges, see #16.
